const {test}=require('node:test');const assert=require('node:assert/strict');const F=require('../dist/farm.js');
test('farm: resources must be mature and storage capacity is enforced',()=>{let s=F.initial();s=F.act(s,{type:'farm_collect'});assert.equal(s.bag.wheat,1);assert.throws(()=>F.act(s,{type:'farm_collect'}),/vuoto|semina/i);s=F.act(s,{type:'farm_plant'});assert.throws(()=>F.act(s,{type:'farm_collect'}),/maturo/i);s.bag.wheat=6;assert.throws(()=>F.act(s,{type:'farm_collect'}),/pieno/i);});
test('farm: production conserves inputs and orders increase indefinitely',()=>{let s=F.initial();s.x=5;s.y=3;s.stock={wheat:8,ore:4,kits:0};s=F.act(s,{type:'farm_craft'});assert.deepEqual(s.stock,{wheat:6,ore:3,kits:1});s.x=7;s=F.act(s,{type:'farm_ship'});assert.equal(s.orders,1);assert.equal(s.coins,20);assert.equal(s.stock.kits,0);assert.equal(F.order(s).quantity,2);assert.throws(()=>F.act(s,{type:'farm_ship'}),/kit/i);s.orders=999;assert.ok(F.order(s).quantity>0);});
test('farm: upgrades require payment and activate autonomous production',()=>{let s=F.initial();assert.throws(()=>F.act(s,{type:'farm_upgrade',upgrade:'harvester'}),/crediti/i);s.coins=200;s=F.act(s,{type:'farm_upgrade',upgrade:'harvester'});assert.equal(s.coins,170);assert.throws(()=>F.act(s,{type:'farm_upgrade',upgrade:'harvester'}),/installato/i);for(let i=0;i<30;i++)s=F.act(s,{type:'wait',seconds:1});assert.ok(s.stock.wheat>0);});
test('farm: invalid actions do not advance state and sensors match state',()=>{const s=F.initial();const copy=JSON.stringify(s);assert.throws(()=>F.act(s,{type:'farm_deposit'}),/magazzino/i);assert.equal(JSON.stringify(s),copy);assert.equal(F.condition(s,'cropReady'),true);assert.equal(F.condition(s,'canCraft'),false);});
test('farm: long waits are accepted and other simulations keep their limits',()=>{const E=require('../dist/engine');let s=F.act(F.initial(),{type:'wait',seconds:3600});assert.equal(s.ticks,3600);assert.equal(s.moves,1);assert.throws(()=>E.act('tank',E.initial('tank'),{type:'wait',seconds:11}),/10/);for(const seconds of [0,-1,1.5,Infinity,NaN])assert.throws(()=>F.act(s,{type:'wait',seconds}),/intero|finito|positivo/i);});
test('farm: paid speed upgrades preserve legacy installations and stop at maximum',()=>{let s=F.initial();s.upgrades.harvester=true;s.coins=1000;assert.equal(F.machine(s,'harvester').interval,12);assert.equal(F.machine(s,'harvester').price,60);s=F.act(s,{type:'farm_boost',upgrade:'harvester'});assert.equal(s.coins,940);assert.equal(F.machine(s,'harvester').interval,8);s=F.act(s,{type:'farm_boost',upgrade:'harvester'});assert.equal(s.coins,820);assert.equal(F.machine(s,'harvester').interval,4);assert.throws(()=>F.act(s,{type:'farm_boost',upgrade:'harvester'}),/massimo/i);assert.throws(()=>F.act(s,{type:'farm_boost',upgrade:'drill'}),/installa/i);s.upgrades.drill=true;s.coins=99;assert.equal(F.condition(s,'canDrillBoost'),false);assert.throws(()=>F.act(s,{type:'farm_boost',upgrade:'drill'}),/100 crediti/);s.coins=100;assert.equal(F.condition(s,'canDrillBoost'),true);});
test('farm: a billion ticks with upgraded machines completes without per-tick work',{timeout:2000},()=>{const s=F.initial();s.upgrades={harvester:3,drill:3,assembler:3};const next=F.act(s,{type:'wait',seconds:1000000000});assert.equal(next.ticks,1000000000);assert.deepEqual(next.stock,{wheat:2,ore:500000001,kits:499999999});assert.equal(next.harvested,1000000000);assert.equal(next.mined,1000000000);assert.equal(next.produced,499999999);});
test('farm: accelerated time matches an independent tick simulation at every speed',()=>{
 function reference(s,n){s=JSON.parse(JSON.stringify(s));const times={harvester:[0,12,8,4],drill:[0,6,3,1],assembler:[0,4,2,1]};for(let i=0;i<n;i++){s.ticks++;for(const p of s.plots)if(p.age!==null)p.age=Math.min(4,p.age+1);if(s.upgrades.harvester&&s.ticks%times.harvester[Number(s.upgrades.harvester)]===0)for(const p of s.plots){if(p.age>=4){s.stock.wheat++;s.harvested++;p.age=0;}else if(p.age===null)p.age=0;}if(s.upgrades.drill&&s.ticks%times.drill[Number(s.upgrades.drill)]===0){s.stock.ore++;s.mined++;}if(s.upgrades.assembler&&s.ticks%times.assembler[Number(s.upgrades.assembler)]===0&&s.stock.wheat>=2&&s.stock.ore>=1){s.stock.wheat-=2;s.stock.ore--;s.stock.kits++;s.produced++;}}s.moves++;s.notice='';return s;}
 for(let h=0;h<=3;h++)for(let d=0;d<=3;d++)for(let a=0;a<=3;a++){const s=F.initial();s.upgrades={harvester:h,drill:d,assembler:a};s.ticks=7;s.stock={wheat:123,ore:91,kits:2};s.plots.forEach((p,i)=>p.age=[null,0,2,4][i]);assert.deepEqual(F.act(s,{type:'wait',seconds:10003}),reference(s,10003),`${h}/${d}/${a}`);}
});
