const {test}=require('node:test');const assert=require('node:assert/strict');const {jsPDF}=require('jspdf');const R=require('../dist/report.js');const E=require('../dist/engine.js');
test('report produces a real paginated PDF including all exercises and factory data',()=>{const saved={profile:{name:'Studente di prova',classe:'5 ITT'},completed:['stack'],activity:{stack:{attempts:2,actions:14,errors:1,successes:1,best:12,result:'Obiettivo raggiunto',lastError:'Pinza vuota',lastProgram:E.solution('stack')}},factory:E.initial('factory')};const doc=R.create(jsPDF,saved,E.missions,new Date('2026-10-07T12:00:00Z'));const pdf=doc.output();assert.ok(pdf.startsWith('%PDF-'));assert.ok(doc.getNumberOfPages()>=3);assert.ok(pdf.includes('Fabbrica'));assert.ok(pdf.includes('Studente di prova'));assert.ok(pdf.includes('Pinza vuota'));});
test('report includes machine levels and production intervals',()=>{const factory=E.initial('factory');factory.upgrades={harvester:3,drill:true,assembler:2};const pdf=R.create(jsPDF,{factory},E.missions).output();assert.ok(pdf.includes('Mietitrice livello 3'));assert.ok(pdf.includes('Trivella livello 1'));assert.ok(pdf.includes('Linea automatica livello 2'));assert.ok(pdf.includes('ogni 2 tick'));});
test('full report exports unused functions, detached drafts and every saved level without changing execution',()=>{
 const B=require('blockly'),A=require('../dist/blockly-adapter');A.define(B);const ws=new B.Workspace();B.serialization.workspaces.load(A.fromFlat([{type:'farm_collect'}]),ws);
 const def=ws.newBlock('procedures_defnoreturn');def.setFieldValue('esempio raccolta','NAME');const incomplete=ws.newBlock('lab_farm_go_value');def.getInput('STACK').connection.connect(incomplete.previousConnection);
 const parked=ws.newBlock('lab_farm_boost');parked.setFieldValue('drill','upgrade');const number=ws.newBlock('math_number');number.setFieldValue(123,'NUM');
 const programs={factory:B.serialization.workspaces.save(ws),path:A.fromFlat([{type:'forward'}])},before=JSON.stringify(programs);
 const drafts=A.reportDrafts(B,programs,E.missions);assert.equal(drafts.length,2);const factory=drafts.find(d=>d.title==='La fabbrica infinita');assert.equal(factory.error,undefined);const lines=R.programLines(factory.program).join('\n');assert.match(lines,/funzione esempio raccolta/);assert.match(lines,/vai a \(\?, \?\)/);assert.match(lines,/staccati/i);assert.match(lines,/potenzia velocità di drill/);assert.match(lines,/123/);assert.deepEqual(A.toFlat(ws).map(b=>b.type),['farm_collect']);assert.equal(JSON.stringify(programs),before);
 const pdf=R.create(jsPDF,{drafts},E.missions).output();assert.ok(pdf.includes('funzione esempio raccolta'));assert.ok(pdf.includes('avanza di 1'));assert.ok(pdf.includes('Codice completo salvato'));ws.dispose();
});
